hmrc/crs-fatca-fi-management-frontend

- app/assets/stylesheets/application.scss
- app/controllers/FirstContactEmailController.scala
- app/forms/FirstContactEmailFormProvider.scala
- app/viewmodels/govuk/LabelFluency.scala
- app/views/FirstContactEmailView.scala.html
- app/views/components/Heading.scala.html
- app/views/components/Paragraph.scala.html
- test/controllers/FirstContactEmailControllerSpec.scala
**part1**
1. “We will use this email address to send confirmation of reports for [FI name] or if we have any questions about them.” should be a paragraph instead of hint text. 
2. In the above paragraph, FI name is the Financial Institution Name. Currently “FI first contact name” from url /contact-name is displayed. 
3. In case of Invalid format and Too long errors, Invalid format error is displayed only once. 
**part2**
5. .wrappable class added to service to prevent future audit failures
6. .visuallyHidden added to LabelFluency for pages where paragraphs appear between the heading and the form (unless its a hint it is not supported otherwise)
> DAC6-2734: QA issues addressed

- app/controllers/IndexController.scala
- app/controllers/SecondContactCanWePhoneController.scala
- app/navigation/Navigator.scala
- app/utils/ContactHelper.scala
- app/views/SecondContactCanWePhoneView.scala.html
- conf/app.routes
- conf/messages.en
- test/base/SpecBase.scala
- test/controllers/SecondContactCanWePhoneControllerSpec.scala
- test/navigation/NavigatorSpec.scala
To test this visit:
- /
- /nameOfFinancialInstitution
- /second-contact-name
- and then /second-contact-have-phone
> DAC6-2738: Add SecondContactCanWePhonePage

- app/config/FrontendAppConfig.scala
- conf/application.conf
Simplified the feedback-frontend config and made it match the contact-frontend config.
Using `baseUrl` meant we had to provide a protocol/host/port combination which is unnecessarily complex for a simple frontend redirect url.
Also spotted and fixed - some of the localhost config was still set at port 9000 rather than the correct 10033 for this service. Updated them.
> DAC6-3131: Updated feedback-frontend config

- app/controllers/IndexController.scala
- app/controllers/addFinancialInstitution/AddFIController.scala
- conf/app.routes
- test/controllers/IndexControllerSpec.scala
- test/controllers/actions/FakeCtUtrRetrievalAction.scala
- test/controllers/addFinancialInstitution/AddFIControllerSpec.scala
We now have one single route for adding an FI - /add - which will decide whether to do the regular add route or present the option of the shorter one.
This means anywhere we have a link to add an FI we can just use this single url and we do not need to worry about the logic of whether they have a CT enrolment or how many FIs they have
> DAC6-3244: Refactored the add FI routing

- app/connectors/RegistrationWithUtrConnector.scala
- app/controllers/CheckDetailsController.scala
- app/controllers/actions/CtUtrRetrievalAction.scala
- app/controllers/actions/DataRequiredAction.scala
- app/controllers/actions/DataRetrievalAction.scala
- app/controllers/addFinancialInstitution/registeredBusiness/IsTheAddressCorrectController.scala
- app/models/AddressResponse.scala
- app/models/RegistrationInfo.scala
- app/models/UniqueTaxpayerReference.scala
- app/models/registration/response/ApiError.scala
- app/models/requests/DataRequest.scala
- app/models/requests/IdentifierRequest.scala
- app/navigation/Navigator.scala
- app/pages/addFinancialInstitution/IsRegisteredBusiness/FetchedRegisteredAddressPage.scala
- app/services/RegistrationWithUtrService.scala
- app/utils/AddressHelper.scala
- app/viewmodels/checkAnswers/WhatIsUniqueTaxpayerReferenceSummary.scala
- app/views/addFinancialInstitution/IsRegisteredBusiness/CheckDetailsView.scala.html
- app/views/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectView.scala.html
- app/views/addFinancialInstitution/IsThisAddressView.scala.html
- app/views/components/AddressBlock.scala.html
- conf/app.routes
- conf/messages.en
- test/base/SpecBase.scala
- test/connectors/RegistrationWithUtrConnectorSpec.scala
- test/controllers/CheckDetailsControllerSpec.scala
- test/controllers/actions/FakeCtUtrRetrievalAction.scala
- test/controllers/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectControllerSpec.scala
- test/navigation/NavigatorSpec.scala
Jira: [DAC6-3231](https://jira.tools.tax.service.gov.uk/browse/DAC6-3231)
-introduces a connector and service to POST to crs-fatca-registration with a utr
-/is-the-address-correct displays the address from the response
-look and feel of this page plus navigation from this page
-scaffolded a placeholder 'checkDetails' (to be developed in another ticket)
-Controller saves fetched address in a Page object
> DAC6-3231: Retrieving the address from Registration for /is-the-address-correct

- app/views/templates/Layout.scala.html
This PR fixes the css class used by the default back link
> DAC6-3336: Fix css class for default back link

- app/controllers/DetailsUpdatedController.scala
- app/controllers/addFinancialInstitution/CheckYourAnswersController.scala
- app/controllers/addFinancialInstitution/IsThisAddressController.scala
- app/handlers/ErrorHandler.scala
- app/models/AddressLookup.scala
- app/models/Country.scala
- app/models/FinancialInstitutions/FIDetail.scala
- app/services/FinancialInstitutionUpdateService.scala
- app/utils/AddressHelper.scala
- test-utils/generators/ModelGenerators.scala
- test/base/SpecBase.scala
- test/connectors/AddressLookupConnectorSpec.scala
- test/controllers/addFinancialInstitution/IsThisAddressControllerSpec.scala
- test/controllers/addFinancialInstitution/PostcodeControllerSpec.scala
- test/controllers/addFinancialInstitution/SelectAddressControllerSpec.scala
- test/services/FinancialInstitutionUpdateServiceSpec.scala
- test/utils/AddressHelperSpec.scala
Refactor the country code from "UK" to "GB" in various models, tests, and utilities. This involves updating instances of "country" throughout AddressLookup, simplifying function and test case logic, and ensuring consistency in address formatting.
> DAC6-3383: Update country code to GB

- test/connectors/AddressLookupConnectorSpec.scala
Included the Country model import to AddressLookupConnectorSpec to ensure the code has access to the necessary classes for address lookup functionality. This change is essential to support the expanded address lookup features.
> BUILD_FIX: Add Country model import

- app/controllers/actions/CtUtrRetrievalAction.scala
- test/controllers/actions/CtUtrRetrievalActionSpec.scala
Added tests for `CtUtrRetrievalAction` to ensure correct functionality. Validated auto-matching behavior for agents and non-agents, confirming correct responses.
> DAC6-3379: Update CtUtrRetrievalAction && add unit tests

- app/models/UserAnswers.scala
- app/services/FinancialInstitutionUpdateService.scala
- app/viewmodels/changeFinancialInstitution/FinancialInstitutionIdSummary.scala
- test/base/SpecBase.scala
- test/controllers/actions/CtUtrRetrievalActionSpec.scala
- test/models/UserAnswersSpec.scala
- test/pages/addFinancialInstitution/AddressPagesSpec.scala
Updated the UserAnswers `set` method to include an optional cleanup flag, allowing control over the cleanup behavior. Modified all existing `set` calls to pass the cleanup flag where necessary and added relevant test cases to verify the new functionality.
> DAC6-3293: Add cleanup flag to UserAnswers set method

- app/controllers/addFinancialInstitution/registeredBusiness/IsTheAddressCorrectController.scala
- app/services/FinancialInstitutionsService.scala
- app/viewmodels/common/package.scala
- conf/messages.en
Changed TIN type from UTR to GIIN in `FinancialInstitutionsService` for correct GIIN processing. Also updated message titles to refer to "registered business" instead of "financial institution".
> DAC6-3293: Update GIIN processing

- app/utils/CheckYourAnswersValidator.scala
- test/controllers/changeFinancialInstitution/ChangeFinancialInstitutionControllerSpec.scala
- test/utils/CheckYourAnswersValidatorSpec.scala
Eliminate all occurrences of PostcodePage from CheckYourAnswersValidator and associated test files. This reduces redundancy and cleans up the codebase by removing an unnecessary page check.
> DAC6-3361: Remove PostcodePage references

- app/assets/javascripts/app.js
- app/models/WhichIdentificationNumbers.scala
- test/controllers/NotInUKControllerSpec.scala
Introduced functionality to handle exclusive behavior for specific checkboxes in both Scala and JavaScript. Updated `WhichIdentificationNumbers` to include exclusive attributes and added JavaScript logic to ensure proper interaction between exclusive and non-exclusive checkboxes. Removed unused import from `NotInUKControllerSpec`.
> DAC6-3413: Add exclusive checkbox logic

- app/models/subscription/response/DisplaySubscriptionResponse.scala
- app/models/subscription/response/UserSubscription.scala
- app/services/SubscriptionService.scala
- test/connectors/SubscriptionConnectorSpec.scala
Refactor `UserSubscription` to nest within `CrfaSubscriptionDetails` for better alignment with API response. Adjust related models and services to accommodate the updated structure.
> DAC6-3471: Update subscription model structure

- app/models/Address.scala
Added custom implementations for `equals` and `hashCode` in the `Address` model to ensure proper comparison and hashing behavior based on address fields. This improves the accuracy of address object comparisons and compatibility with collections.
> DAC6-3458: Define equals and hashCode

- app/viewmodels/common/package.scala
Updated pattern matching to remove unnecessary strictness for `addressLookup` in UK address condition. This ensures more robust and maintainable logic for determining address types.
> DAC6-3447: Simplify address logic

- app/controllers/DetailsUpdatedController.scala
- app/views/DetailsUpdatedView.scala.html
- conf/messages.en
- test/controllers/DetailsUpdatedControllerSpec.scala
Because we are using flash storage to carry the financial institution name safely to the /details-updated page (after useranswers are cleared)- once the user moves away this will be lost and so ive added the default 'the financial institution' in place of missing data should the user redirect and return to this page.
> DAC6-3432: handle missing fiName with default text

- app/controllers/changeFinancialInstitution/ChangeFinancialInstitutionController.scala
- app/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionController.scala
- app/services/FinancialInstitutionUpdateService.scala
- test/controllers/changeFinancialInstitution/ChangeFinancialInstitutionControllerSpec.scala
- test/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionControllerSpec.scala
- test/services/FinancialInstitutionUpdateServiceSpec.scala
Modified `populateAndSaveFiDetails` and `populateAndSaveRegisteredFiDetails` to return a tuple with user answers and change status. Updated related controller and test code to handle the new return type appropriately.
> DAC6-3513: Update FI details persistence logic

- app/controllers/addFinancialInstitution/registeredBusiness/IsThisYourBusinessNameController.scala
Updated the repository call to use the correct variable `updatedFIName` instead of `updatedAnswers`. This ensures the correct data is saved and prevents potential inconsistencies.
> DAC6-3417: Fix incorrect variable in repository update

- .g8/checkboxPage/app/views/$className$View.scala.html
- .g8/datePage/app/views/$className$View.scala.html
- .g8/intPage/app/views/$className$View.scala.html
- .g8/multipleQuestionsPage/app/views/$className$View.scala.html
- .g8/radioButtonPage/app/views/$className$View.scala.html
- .g8/yesNoPage/app/views/$className$View.scala.html
- app/views/RemoveAreYouSureView.scala.html
- app/views/YourFinancialInstitutionsView.scala.html
- app/views/addFinancialInstitution/FirstContactEmailView.scala.html
- app/views/addFinancialInstitution/FirstContactHavePhoneView.scala.html
- app/views/addFinancialInstitution/FirstContactNameView.scala.html
- app/views/addFinancialInstitution/FirstContactPhoneNumberView.scala.html
- app/views/addFinancialInstitution/HaveGIINView.scala.html
- app/views/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectView.scala.html
- app/views/addFinancialInstitution/IsRegisteredBusiness/IsThisYourBusinessNameView.scala.html
- app/views/addFinancialInstitution/IsRegisteredBusiness/ReportForRegisteredBusinessView.scala.html
- app/views/addFinancialInstitution/IsThisAddressView.scala.html
- app/views/addFinancialInstitution/NameOfFinancialInstitutionView.scala.html
- app/views/addFinancialInstitution/PostcodeView.scala.html
- app/views/addFinancialInstitution/SecondContactCanWePhoneView.scala.html
- app/views/addFinancialInstitution/SecondContactEmailView.scala.html
- app/views/addFinancialInstitution/SecondContactExistsView.scala.html
- app/views/addFinancialInstitution/SecondContactNameView.scala.html
- app/views/addFinancialInstitution/SecondContactPhoneNumberView.scala.html
- app/views/addFinancialInstitution/SelectAddressView.scala.html
- app/views/addFinancialInstitution/UkAddressView.scala.html
- app/views/addFinancialInstitution/WhatIsCompanyRegistrationNumberView.scala.html
- app/views/addFinancialInstitution/WhatIsGIINView.scala.html
- app/views/addFinancialInstitution/WhatIsUniqueTaxpayerReferenceView.scala.html
- app/views/addFinancialInstitution/WhichIdentificationNumbersView.scala.html
Updated formHelper instances across multiple views to enable autoComplete by setting Symbol("autoComplete") to "on". This improves user experience by allowing browsers to suggest and autofill inputs where applicable.
> DAC6-3538: Enable form autoComplete

- app/models/FinancialInstitutions/FIDetail.scala
- app/services/FinancialInstitutionsService.scala
- test-utils/generators/ModelGenerators.scala
- test/base/SpecBase.scala
- test/connectors/FinancialInstitutionsConnectorSpec.scala
Eliminated the IsFATCAReporting field and all related code references to simplify the FinancialInstitutions data model. This change reduces redundancy and improves code maintainability across the models, services, and test cases.
> DAC6-3602: Remove IsFATCAReporting field

- app/controllers/FIRemovedController.scala
- app/models/FinancialInstitutions/FIDetail.scala
- app/models/FinancialInstitutions/TINType.scala
- app/services/FinancialInstitutionUpdateService.scala
- app/services/FinancialInstitutionsService.scala
- test-utils/generators/ModelGenerators.scala
- test/base/SpecBase.scala
- test/connectors/FinancialInstitutionsConnectorSpec.scala
- test/services/FinancialInstitutionUpdateServiceSpec.scala
Simplify GIIN handling by decoupling it from TINDetails and introducing a dedicated field in FIDetail. This improves clarity, reduces complexity, and removes redundant checks for GIIN in TINType workflows.
> DAC6-3609: Refactor FI logic to separate GIIN

- app/forms/mappings/Constraints.scala
- app/models/FinancialInstitutions/TINType.scala
- app/navigation/Navigator.scala
- app/pages/addFinancialInstitution/WhichIdentificationNumbersPage.scala
- app/services/FinancialInstitutionUpdateService.scala
- app/services/FinancialInstitutionsService.scala
- app/utils/CheckYourAnswersValidator.scala
- app/viewmodels/common/package.scala
- conf/messages.en
- test-utils/generators/ModelGenerators.scala
- test/navigation/CheckModeNavigatorSpec.scala
- test/navigation/NavigatorSpec.scala
- test/pages/addFinancialInstitution/WhichIdentificationNumbersPageSpec.scala
- test/services/FinancialInstitutionUpdateServiceSpec.scala
- test/viewmodels/checkAnswers/CheckYourAnswersViewModelSpec.scala
Renamed all instances of 'TRN' to 'TURN' in TINType and related logic to improve consistency and clarity. Updated affected navigation, validation, and test cases to reflect the changes.
> DAC6-3633: Rename TRN to TURN

- test-utils/generators/Generators.scala
- test-utils/generators/ModelGenerators.scala
Replaced repetitive `arbitrary[String].suchThat(_.nonEmpty)` with a reusable `nonEmptyString` method for cleaner and more consistent generator definitions. Updated affected tests and model generators to leverage this new utility.
> DAC6-3672: Refactor generators to use nonEmptyString

- app/controllers/addFinancialInstitution/CheckYourAnswersController.scala
- app/forms/addFinancialInstitution/NonUkAddressFormProvider.scala
- app/forms/addFinancialInstitution/UkAddressFormProvider.scala
- app/models/Address.scala
- app/models/AddressLookup.scala
- app/models/AddressResponse.scala
- app/models/FinancialInstitutions/FIDetail.scala
- project/AppDependencies.scala
- test-utils/generators/ModelGenerators.scala
- test/base/SpecBase.scala
- test/connectors/FinancialInstitutionsConnectorSpec.scala
- test/controllers/addFinancialInstitution/IsThisAddressControllerSpec.scala
- test/controllers/addFinancialInstitution/UkAddressControllerSpec.scala
- test/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionControllerSpec.scala
- test/forms/addFinancialInstitution/NonUkAddressFormProviderSpec.scala
- test/forms/addFinancialInstitution/UkAddressFormProviderSpec.scala
- test/utils/AddressHelperSpec.scala
Updated `Address` and related classes to make `addressLine3` optional. Adjusted forms, views, and tests to accommodate this change and ensure compatibility across the application.
> DAC6-3786: Make `addressLine3` optional

- app/assets/stylesheets/application.scss
- app/viewmodels/yourFinancialInstitutions/YourFinancialInstitutionsViewModel.scala
- app/views/YourFinancialInstitutionsView.scala.html
- project/AppDependencies.scala
- test/views/YourFinancialInstitutionsViewSpec.scala
Introduced `YourFinancialInstitutionsViewSpec` to validate rendering of key view components for financial institutions. Simplified view layout styling by removing redundant CSS and aligning summary list with GOV.UK design standards.
> DAC6-3814: Fix YourFinancialInstitutionsView

- app/forms/mappings/Transforms.scala
- test/forms/addFinancialInstitution/WhatIsGIINFormProviderSpec.scala
- test/forms/behaviours/FieldBehaviours.scala
Ticket: https://jira.tools.tax.service.gov.uk/browse/DAC6-3812
1. Changed the app/forms/mappings/Transforms.scala to strip out empty spaces.
2. Updated unit tests
>  DAC6-3812 - Accessibility Audit: CRS/FATCA: Issue 9672: Validation does not accommodate spaces (P1)
