hmrc/crs-fatca-fi-management-frontend

app/controllers/ContactNameController.scala, conf/app.routes, test/controllers/ContactNameControllerSpec.scala
[DAC6-2733](https://jira.tools.tax.service.gov.uk/browse/DAC6-2733)
=> DAC6-2733: initiate user answers

app/views/FirstContactEmailView.scala.html, conf/messages.en
=> DAC6-2734: generic title for security reasons

app/controllers/SecondContactPhoneNumberController.scala, app/forms/SecondContactPhoneNumberFormProvider.scala, app/navigation/Navigator.scala, app/views/SecondContactPhoneNumberView.scala.html, conf/app.routes, conf/messages.en, test/controllers/SecondContactPhoneNumberControllerSpec.scala, test/forms/SecondContactPhoneNumberFormProviderSpec.scala, test/navigation/NavigatorSpec.scala
=> Dac6-2739: Second Contact Phone Number

app/navigation/Navigator.scala, test/navigation/NavigatorSpec.scala
Navigation completed and tested for contact details part of journey
=> DAC6-2958: Navigation

app/controllers/HaveUniqueTaxpayerReferenceController.scala, app/navigation/Navigator.scala, app/utils/ContactHelper.scala, app/viewmodels/govuk/FieldsetFluency.scala, app/views/HaveUniqueTaxpayerReferenceView.scala.html, conf/app.routes, conf/messages.en, test/controllers/HaveUniqueTaxpayerReferenceControllerSpec.scala, test/navigation/NavigatorSpec.scala
[DAC6-2741](https://jira.tools.tax.service.gov.uk/browse/DAC6-2741)
=> Dac6-2741: Does FI have UTR page

app/controllers/HaveGIINController.scala, app/navigation/Navigator.scala, app/views/HaveGIINView.scala.html, conf/app.routes, conf/messages.en, test/controllers/HaveGIINControllerSpec.scala, test/navigation/NavigatorSpec.scala
[DAC6-2987](https://jira.tools.tax.service.gov.uk/browse/DAC6-2987)
=> DAC6-2987: /have-GIIN page

conf/logback.xml, conf/messages.en
=> CYA Label fix

app/controllers/addFinancialInstitution/CheckYourAnswersController.scala, app/views/addFinancialInstitution/CheckYourAnswersView.scala.html, conf/messages.en, test/base/SpecBase.scala, test/controllers/addFinancialInstitution/CheckYourAnswersControllerSpec.scala, test/controllers/addFinancialInstitution/FirstContactEmailControllerSpec.scala, test/controllers/addFinancialInstitution/FirstContactHavePhoneControllerSpec.scala, test/controllers/addFinancialInstitution/FirstContactNameControllerSpec.scala, test/controllers/addFinancialInstitution/HaveGIINControllerSpec.scala, test/controllers/addFinancialInstitution/HaveUniqueTaxpayerReferenceControllerSpec.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectControllerSpec.scala, test/controllers/addFinancialInstitution/IsThisAddressControllerSpec.scala, test/controllers/addFinancialInstitution/NonUkAddressControllerSpec.scala, test/controllers/addFinancialInstitution/SecondContactCanWePhoneControllerSpec.scala, test/controllers/addFinancialInstitution/SecondContactEmailControllerSpec.scala, test/controllers/addFinancialInstitution/SecondContactNameControllerSpec.scala, test/controllers/addFinancialInstitution/UkAddressControllerSpec.scala, test/controllers/addFinancialInstitution/WhatIsUniqueTaxpayerReferenceControllerSpec.scala
=> PATCH: Make CYA heading dynamic plus spec val refactor 

app/models/AddressResponse.scala
=> DAC6-3231: convert country code to name for GB

app/models/AddressResponse.scala
used for AddressResponse conversion to lines of strings
=> PATCH: introduce postcode formatter from reg service

app/config/CryptoProvider.scala, app/config/FrontendAppConfig.scala, app/config/Module.scala, app/models/CryptoType.scala, app/models/UserAnswers.scala, app/models/crypto/SensitiveJsObject.scala, app/repositories/SessionRepository.scala, conf/application.conf, it/test/repositories/SessionRepositorySpec.scala, project/AppDependencies.scala
- Also added CryptoType object contaning type alias CryptoT and relevant vals
=> DAC6-3220: Encrypt User Answers for FI Management

app/views/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersView.scala.html, conf/messages.en
**Identification number -> Identification Number** across service
**Confirm and Add -> Confirm and Send** on RegCYA
=> DAC6-3044: content update

app/controllers/YourFinancialInstitutionsController.scala, app/controllers/addFinancialInstitution/FinancialInstitutionAddedConfirmationController.scala, app/navigation/Navigator.scala, app/views/FinancialInstitutionAddedConfirmationView.scala.html, app/views/YourFinancialInstitutionsView.scala.html, conf/app.routes, conf/messages.en, test/controllers/YourFinancialInstitutionsControllerSpec.scala, test/controllers/addFinancialInstitution/FinancialInstitutionAddedConfirmationControllerSpec.scala
=> DAC6-3046: Create Add FI Confirmation page

app/connectors/FinancialInstitutionsConnector.scala, app/controllers/addFinancialInstitution/registeredBusiness/RegisteredBusinessCheckYourAnswersController.scala, app/models/AddressResponse.scala, app/models/FinancialInstitutions/FIDetail.scala, app/services/FinancialInstitutionsService.scala, app/utils/CheckYourAnswersValidator.scala, app/views/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersView.scala.html, conf/app.routes, test-utils/generators/UserAnswersEntryGenerators.scala, test-utils/generators/UserAnswersGenerator.scala, test/connectors/FinancialInstitutionsConnectorSpec.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersControllerSpec.scala, test/helpers/WireMockServerHandler.scala, test/services/FinancialInstitutionsServiceSpec.scala
Implemented functionality to add financial institution details including connectors, services, and tests. Updated views and routes to support the new feature.
=> DAC6-3328: Add Financial Institution feature

app/controllers/SomeInformationMissingController.scala, app/controllers/addFinancialInstitution/CheckYourAnswersController.scala, app/controllers/addFinancialInstitution/registeredBusiness/RegisteredBusinessCheckYourAnswersController.scala, app/navigation/Navigator.scala, app/utils/CheckYourAnswersValidator.scala, app/views/SomeInformationMissingView.scala.html, test-utils/generators/ModelGenerators.scala, test-utils/generators/UserAnswersEntryGenerators.scala, test-utils/generators/UserAnswersGenerator.scala, test/controllers/SomeInformationMissingControllerSpec.scala, test/controllers/addFinancialInstitution/CheckYourAnswersControllerSpec.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersControllerSpec.scala, test/utils/CheckYourAnswersValidatorSpec.scala
also added Some Information continue button and logic to determine where to send user
=> DAC6-3209 Added CYA Validation implementation to both CYA and registered business CYA

app/connectors/FinancialInstitutionsConnector.scala, app/controllers/RemoveAreYouSureController.scala, app/models/FinancialInstitutions/FIDetail.scala, app/services/FinancialInstitutionsService.scala, test/connectors/FinancialInstitutionsConnectorSpec.scala, test/controllers/RemoveAreYouSureControllerSpec.scala, test/services/FinancialInstitutionsServiceSpec.scala
-to be reviewed with Backend and Stub
=> DAC- 3187: Send Remove an FI details to CADX

app/controllers/addFinancialInstitution/registeredBusiness/IsTheAddressCorrectController.scala, app/models/AddressResponse.scala
Refactored AddressResponse to include an optional Country field for better encapsulation. Updated IsTheAddressCorrectController to handle the new country field, ensuring country descriptions are used when available and handling errors appropriately.
=> DAC6-3342: Add country to AddressResponse

project/AppDependencies.scala, project/plugins.sbt
Upgraded sbt-plugin, bootstrap-frontend, play-frontend-hmrc, play-conditional-form-mapping, and crypto-json-play to their latest versions. This will include the latest features and bug fixes, ensuring the project is up-to-date with current standards.
=> DAC6-3330: Update dependencies

app/connectors/AddressLookupConnector.scala, app/connectors/RegistrationWithUtrConnector.scala, app/connectors/SubscriptionConnector.scala
=> [TECH-DEBT]: replace deprecated client

app/controllers/DetailsUpdatedController.scala, app/controllers/addFinancialInstitution/CheckYourAnswersController.scala, app/controllers/addFinancialInstitution/IsThisAddressController.scala, app/handlers/ErrorHandler.scala, test-utils/generators/Generators.scala, test/connectors/AddressLookupConnectorSpec.scala
=> [tech-debt]: solve warnings

app/controllers/addFinancialInstitution/UkAddressController.scala, app/forms/addFinancialInstitution/UkAddressFormProvider.scala, app/views/addFinancialInstitution/UkAddressView.scala.html, conf/messages.en, test/controllers/addFinancialInstitution/UkAddressControllerSpec.scala, test/forms/addFinancialInstitution/UkAddressFormProviderSpec.scala
Remove country input, add validation
=> DAC6-3388: update addressUk page

app/controllers/SomeInformationMissingController.scala, app/controllers/changeFinancialInstitution/ChangeFinancialInstitutionController.scala, app/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionController.scala, app/utils/CheckYourAnswersValidator.scala, test/controllers/changeFinancialInstitution/ChangeFinancialInstitutionControllerSpec.scala, test/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionControllerSpec.scala, test/utils/CheckYourAnswersValidatorSpec.scala
Refactor CheckYourAnswersValidator to provide more detailed and correct page redirections based on missing answers. Introduced methods to handle redirection for both regular and registered businesses more effectively, aligning the functionality across various controllers. Updated related tests to ensure comprehensive coverage.
=> DAC6-3361: Refactor CheckYourAnswersValidator

app/models/AddressResponse.scala, app/viewmodels/common/package.scala, test/viewmodels/checkAnswers/CheckYourAnswersViewModelSpec.scala
- Remove country from main address
- redirect to postcode on changelink
https://github.com/user-attachments/assets/ec0d8da9-2ef4-403c-b614-f3c745b67a51
=> Dac6 3392: Standard /change-answers address changes

app/config/FrontendAppConfig.scala, app/controllers/addFinancialInstitution/WhatIsCompanyRegistrationNumberController.scala, app/forms/addFinancialInstitution/CompanyRegistrationNumberFormProvider.scala, app/forms/mappings/Formatters.scala, app/forms/mappings/Mappings.scala, app/models/TaxIdentificationNumber.scala, app/utils/RegexConstants.scala, app/viewmodels/govuk/InputFluency.scala, app/views/addFinancialInstitution/WhatIsCompanyRegistrationNumberView.scala.html, conf/app.routes, conf/application.conf, conf/messages.en, test-utils/generators/Generators.scala, test/controllers/addFinancialInstitution/WhatIsCompanyRegistrationNumberControllerSpec.scala, test/forms/addFinancialInstitution/CompanyRegistrationNumberFormProviderSpec.scala
Introduce a form for capturing Company Registration Number (CRN) including its validations and relevant view. This commit includes a controller, form provider, messages, and the tests necessary for handling CRN.
=> DAC6-3402: Add Company Registration Number form

app/viewmodels/checkAnswers/NonUkAddressSummary.scala, app/viewmodels/checkAnswers/SelectedAddressLookupSummary.scala, app/viewmodels/checkAnswers/UkAddressSummary.scala, app/viewmodels/common/FetchedRegisteredAddressSummary.scala, app/viewmodels/common/package.scala, test/viewmodels/checkAnswers/CheckYourAnswersViewModelSpec.scala
restore change address logic based on fi=user or not
=> DAC6-3456[BUG]: change main address

app/controllers/addFinancialInstitution/WhichIdentificationNumbersController.scala, app/forms/addFinancialInstitution/WhichIdentificationNumbersFormProvider.scala, app/forms/mappings/Constraints.scala, app/models/WhichIdentificationNumbers.scala, app/pages/addFinancialInstitution/WhichIdentificationNumbersPage.scala, app/viewmodels/checkAnswers/WhichIdentificationNumbersSummary.scala, app/viewmodels/govuk/CheckboxFluency.scala, app/views/addFinancialInstitution/WhichIdentificationNumbersView.scala.html, conf/app.routes, conf/messages.en, test-utils/generators/ModelGenerators.scala, test/controllers/addFinancialInstitution/WhichIdentificationNumbersControllerSpec.scala, test/forms/addFinancialInstitution/WhichIdentificationNumbersFormProviderSpec.scala, test/models/WhichIdentificationNumbersSpec.scala
=> Dac6 3400: Create new page /identification-numbers

.g8/checkboxPage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/datePage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/intPage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/multipleQuestionsPage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/radioButtonPage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/stringPage/app/viewmodels/checkAnswers/$className$Summary.scala, .g8/yesNoPage/app/viewmodels/checkAnswers/$className$Summary.scala, app/viewmodels/changeFinancialInstitution/FinancialInstitutionIdSummary.scala
All new pages made use ActionItemViewModel, we should update change links to use accessibleActionItem so we don't have to remember to change them :)
=> Update templates to use accessibleActionItem

app/views/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionView.scala.html, conf/messages.en
=> Dac6 3426: Update change-FI CYA content

conf/messages.en
=> DAC6-3514: update timeout content

app/controllers/OtherAccessController.scala, app/controllers/RemoveAreYouSureController.scala, app/forms/OtherAccessFormProvider.scala, app/forms/mappings/Formatters.scala, app/pages/RemoveAreYouSurePage.scala, app/views/OtherAccessView.scala.html, app/views/RemoveAreYouSureView.scala.html, conf/app.routes, conf/messages.en, test/controllers/OtherAccessControllerSpec.scala, test/controllers/RemoveAreYouSureControllerSpec.scala, test/forms/OtherAccessFormProviderSpec.scala, test/pages/RemoveAreYouSurePageSpec.scala
3464 - remove-fi page 
3463 - other-access page
=> Dac6 3463-3464: Remove journey

app/viewmodels/checkAnswers/ReportForRegisteredBusinessSummary.scala, app/viewmodels/common/FirstContactNameSummary.scala, app/viewmodels/common/IsThisYourBusinessNameSummary.scala, app/viewmodels/common/NameOfFinancialInstitutionSummary.scala, app/viewmodels/common/SecondContactNameSummary.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersControllerSpec.scala
used Text component as per doc
=> Used Text component to handle dynamic data

app/viewmodels/yourFinancialInstitutions/YourFinancialInstitutionsViewModel.scala, app/views/YourFinancialInstitutionsView.scala.html, app/views/templates/Layout.scala.html, test/base/SpecBase.scala, test/viewmodels/yourFinancialInstitutions/YourFinancialInstitutionsViewModelSpec.scala
=> Dac6 3460: Update /your-fis, add tag and sort FIs alphabetically

app/assets/stylesheets/application.scss, app/views/templates/Layout.scala.html
- table wrapping
- line-height
- restrict column to main width
=> Dac6 3460: fixes

app/forms/addFinancialInstitution/FirstContactPhoneNumberFormProvider.scala, app/forms/addFinancialInstitution/SecondContactPhoneNumberFormProvider.scala, app/utils/RegexConstants.scala, test/forms/addFinancialInstitution/FirstContactPhoneNumberFormProviderSpec.scala, test/forms/addFinancialInstitution/SecondContactPhoneNumberFormProviderSpec.scala
Fixed regex 
Added test with invalid data set
=> fixed regex for telephone number

app/viewmodels/changeFinancialInstitution/FinancialInstitutionIdSummary.scala
=> DAC6-3649: remove action from row

app/views/addFinancialInstitution/SecondContactNameView.scala.html, conf/messages.en
=> DAC6-3667: correct hint type

app/views/addFinancialInstitution/SecondContactNameView.scala.html
=> DAC6-3687: change width

app/controllers/addFinancialInstitution/registeredBusiness/IsTheAddressCorrectController.scala, app/services/FinancialInstitutionUpdateService.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectControllerSpec.scala, test/services/FinancialInstitutionUpdateServiceSpec.scala
Removed incorrect setup of ISTheAddressCorrect for AllRegFI
Added condition for changeFI in ISTheAddressCorrect
Added Postcode Page value during setting Address
=> DAC6-3684 : update IsTheAddressCorrect logic for change FI Flow

app/controllers/addFinancialInstitution/FinancialInstitutionAddedConfirmationController.scala, app/controllers/addFinancialInstitution/SelectAddressController.scala, app/pages/addFinancialInstitution/IsRegisteredBusiness/FetchedRegisteredAddressPage.scala, app/pages/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectPage.scala, app/pages/addFinancialInstitution/UkAddressPage.scala, build.sbt, conf/application.conf, project/AppDependencies.scala, test/pages/addFinancialInstitution/IsRegisteredBusiness/FetchedRegisteredAddressPageSpec.scala, test/pages/addFinancialInstitution/IsRegisteredBusiness/IsTheAddressCorrectPageSpec.scala, test/pages/addFinancialInstitution/SelectedAddressLookupPageSpec.scala, test/pages/addFinancialInstitution/UkAddressPageSpec.scala
No longer remove AddressLookup data onSubmit
[DAC6-3686](https://jira.tools.tax.service.gov.uk/browse/DAC6-3686)
=> DAC6-3686 | Unexpected 'back' behaviour

app/utils/CheckYourAnswersValidator.scala, test-utils/generators/UserAnswersEntryGenerators.scala, test-utils/generators/UserAnswersGenerator.scala, test/base/SpecBase.scala, test/controllers/addFinancialInstitution/IsRegisteredBusiness/RegisteredBusinessCheckYourAnswersControllerSpec.scala, test/controllers/changeFinancialInstitution/ChangeRegisteredFinancialInstitutionControllerSpec.scala, test/navigation/CheckModeNavigatorSpec.scala, test/utils/CheckYourAnswersValidatorSpec.scala
Added condition to check if IsThisAddressCorrect is true then default address should be GB
Existing navigation works as expected
=> DAC6-3688 | added check for reg fi default address to be GB Address

test/services/FinancialInstitutionUpdateServiceSpec.scala
=> DAC6-3710 | added test for regFIUpdate method

app/viewmodels/yourFinancialInstitutions/YourFinancialInstitutionsViewModel.scala
this was to pass visuallyHiddenText
=> DAC6-3858 | Changed AccessibleAutoComplete to ListWithActionsAction

app/forms/mappings/Formatters.scala
Ticket: https://jira.tools.tax.service.gov.uk/browse/DAC6-3812
As per Jill's comments I have reordered the validation rules.
=>  DAC6-3812 - Reordering the validation rules
